version: 2
updates:
- package-ecosystem: maven"
  directory: "/"
  schedule:
    interval: "daily"
    time: "17:10"
  target-branch: "feature/update-dependabot-integration"  
  open-pull-requests-limit: 10
